import { MigrationInterface, QueryRunner } from "typeorm";

export class addPasswordsaltIvAndUpdateUuidGen1682014690006 implements MigrationInterface {
    name = 'addPasswordsaltIvAndUpdateUuidGen1682014690006'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "account" ADD "passwordSalt" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "account" ADD "iv" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "account" ADD "refreshTokenSalt" character varying`);
        await queryRunner.query(`ALTER TABLE "account" ALTER COLUMN "createAt" SET DEFAULT '2023-04-20T18:18:10.608Z'`);
        await queryRunner.query(`ALTER TABLE "category_locations_location" DROP CONSTRAINT "FK_c9d7b40237cebf546efb44be330"`);
        await queryRunner.query(`ALTER TABLE "category" DROP CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03"`);
        await queryRunner.query(`ALTER TABLE "category" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "category" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "category" ADD CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "review" DROP CONSTRAINT "FK_b4e9d4998a69f9a84693757eb87"`);
        await queryRunner.query(`ALTER TABLE "trip_type" DROP CONSTRAINT "PK_b80a1e112ae33caa104b8fd0e39"`);
        await queryRunner.query(`ALTER TABLE "trip_type" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "trip_type" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "trip_type" ADD CONSTRAINT "PK_b80a1e112ae33caa104b8fd0e39" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "review" ALTER COLUMN "reviewDate" SET DEFAULT '2023-04-20T18:18:10.614Z'`);
        await queryRunner.query(`ALTER TABLE "review" DROP CONSTRAINT "UQ_b4e9d4998a69f9a84693757eb87"`);
        await queryRunner.query(`ALTER TABLE "review" DROP COLUMN "tripTypeId"`);
        await queryRunner.query(`ALTER TABLE "review" ADD "tripTypeId" uuid`);
        await queryRunner.query(`ALTER TABLE "review" ADD CONSTRAINT "UQ_b4e9d4998a69f9a84693757eb87" UNIQUE ("tripTypeId")`);
        await queryRunner.query(`ALTER TABLE "location_image" DROP CONSTRAINT "PK_dfa981be0cd5c3c2f8c37915564"`);
        await queryRunner.query(`ALTER TABLE "location_image" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "location_image" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "location_image" ADD CONSTRAINT "PK_dfa981be0cd5c3c2f8c37915564" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "hotel_property_amenities_property_amenity" DROP CONSTRAINT "FK_4b88b59f78c111f3064df52dc1f"`);
        await queryRunner.query(`ALTER TABLE "property_amenity" DROP CONSTRAINT "PK_9a5289e5f83bc78d0dbf997a56f"`);
        await queryRunner.query(`ALTER TABLE "property_amenity" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "property_amenity" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "property_amenity" ADD CONSTRAINT "PK_9a5289e5f83bc78d0dbf997a56f" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "hotel_hotel_styles_hotel_style" DROP CONSTRAINT "FK_c6e80d671f4494cd4c00033f5d0"`);
        await queryRunner.query(`ALTER TABLE "hotel_style" DROP CONSTRAINT "PK_52239cf25eaead597a583e26766"`);
        await queryRunner.query(`ALTER TABLE "hotel_style" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "hotel_style" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "hotel_style" ADD CONSTRAINT "PK_52239cf25eaead597a583e26766" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "hotel_languages_language" DROP CONSTRAINT "FK_8457bf1103d317e3a87aeefd39e"`);
        await queryRunner.query(`ALTER TABLE "language" DROP CONSTRAINT "PK_cc0a99e710eb3733f6fb42b1d4c"`);
        await queryRunner.query(`ALTER TABLE "language" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "language" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "language" ADD CONSTRAINT "PK_cc0a99e710eb3733f6fb42b1d4c" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "room_room_features_room_feature" DROP CONSTRAINT "FK_144c973be949a5ea0b81fc16d77"`);
        await queryRunner.query(`ALTER TABLE "room_feature" DROP CONSTRAINT "PK_06829e5737733d39a047f775a66"`);
        await queryRunner.query(`ALTER TABLE "room_feature" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "room_feature" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "room_feature" ADD CONSTRAINT "PK_06829e5737733d39a047f775a66" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "room_room_types_room_type" DROP CONSTRAINT "FK_6ae9dfc32226d4bdd53353f052a"`);
        await queryRunner.query(`ALTER TABLE "room_type" DROP CONSTRAINT "PK_abd0f8a4c8a444a84fa2b343353"`);
        await queryRunner.query(`ALTER TABLE "room_type" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "room_type" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "room_type" ADD CONSTRAINT "PK_abd0f8a4c8a444a84fa2b343353" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "room_bed" DROP CONSTRAINT "FK_2f701a2444a9499a40659442b80"`);
        await queryRunner.query(`ALTER TABLE "bed" DROP CONSTRAINT "PK_828b3f79eab8a8b1de6b6ed6c5a"`);
        await queryRunner.query(`ALTER TABLE "bed" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "bed" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "bed" ADD CONSTRAINT "PK_828b3f79eab8a8b1de6b6ed6c5a" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "room_bed" DROP COLUMN "bedId"`);
        await queryRunner.query(`ALTER TABLE "room_bed" ADD "bedId" uuid`);
        await queryRunner.query(`ALTER TABLE "receipt" ALTER COLUMN "createAt" SET DEFAULT '2023-04-20T18:18:10.620Z'`);
        await queryRunner.query(`ALTER TABLE "booking" ALTER COLUMN "createAt" SET DEFAULT '2023-04-20T18:18:10.620Z'`);
        await queryRunner.query(`ALTER TABLE "category_locations_location" DROP CONSTRAINT "PK_26b6e9028d7c597535350b05bc4"`);
        await queryRunner.query(`ALTER TABLE "category_locations_location" ADD CONSTRAINT "PK_16c0a15a534e3f86e5dbf1757b9" PRIMARY KEY ("locationId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9d7b40237cebf546efb44be33"`);
        await queryRunner.query(`ALTER TABLE "category_locations_location" DROP COLUMN "categoryId"`);
        await queryRunner.query(`ALTER TABLE "category_locations_location" ADD "categoryId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "category_locations_location" DROP CONSTRAINT "PK_16c0a15a534e3f86e5dbf1757b9"`);
        await queryRunner.query(`ALTER TABLE "category_locations_location" ADD CONSTRAINT "PK_26b6e9028d7c597535350b05bc4" PRIMARY KEY ("locationId", "categoryId")`);
        await queryRunner.query(`ALTER TABLE "room_room_features_room_feature" DROP CONSTRAINT "PK_379ccbfb1b706c0014f653870e2"`);
        await queryRunner.query(`ALTER TABLE "room_room_features_room_feature" ADD CONSTRAINT "PK_7f8b1acbd9e3fc084c43734bd9b" PRIMARY KEY ("roomId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_144c973be949a5ea0b81fc16d7"`);
        await queryRunner.query(`ALTER TABLE "room_room_features_room_feature" DROP COLUMN "roomFeatureId"`);
        await queryRunner.query(`ALTER TABLE "room_room_features_room_feature" ADD "roomFeatureId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "room_room_features_room_feature" DROP CONSTRAINT "PK_7f8b1acbd9e3fc084c43734bd9b"`);
        await queryRunner.query(`ALTER TABLE "room_room_features_room_feature" ADD CONSTRAINT "PK_379ccbfb1b706c0014f653870e2" PRIMARY KEY ("roomId", "roomFeatureId")`);
        await queryRunner.query(`ALTER TABLE "room_room_types_room_type" DROP CONSTRAINT "PK_090c4a3b7469fb4cd3d9df38475"`);
        await queryRunner.query(`ALTER TABLE "room_room_types_room_type" ADD CONSTRAINT "PK_a7acd938565a8daf63a8f352f41" PRIMARY KEY ("roomId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ae9dfc32226d4bdd53353f052"`);
        await queryRunner.query(`ALTER TABLE "room_room_types_room_type" DROP COLUMN "roomTypeId"`);
        await queryRunner.query(`ALTER TABLE "room_room_types_room_type" ADD "roomTypeId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "room_room_types_room_type" DROP CONSTRAINT "PK_a7acd938565a8daf63a8f352f41"`);
        await queryRunner.query(`ALTER TABLE "room_room_types_room_type" ADD CONSTRAINT "PK_090c4a3b7469fb4cd3d9df38475" PRIMARY KEY ("roomId", "roomTypeId")`);
        await queryRunner.query(`ALTER TABLE "hotel_property_amenities_property_amenity" DROP CONSTRAINT "PK_f1d5ba5e12b8dfc56db6089307a"`);
        await queryRunner.query(`ALTER TABLE "hotel_property_amenities_property_amenity" ADD CONSTRAINT "PK_a125ce628f13d8dcd15115e4f8e" PRIMARY KEY ("hotelId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b88b59f78c111f3064df52dc1"`);
        await queryRunner.query(`ALTER TABLE "hotel_property_amenities_property_amenity" DROP COLUMN "propertyAmenityId"`);
        await queryRunner.query(`ALTER TABLE "hotel_property_amenities_property_amenity" ADD "propertyAmenityId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hotel_property_amenities_property_amenity" DROP CONSTRAINT "PK_a125ce628f13d8dcd15115e4f8e"`);
        await queryRunner.query(`ALTER TABLE "hotel_property_amenities_property_amenity" ADD CONSTRAINT "PK_f1d5ba5e12b8dfc56db6089307a" PRIMARY KEY ("hotelId", "propertyAmenityId")`);
        await queryRunner.query(`ALTER TABLE "hotel_hotel_styles_hotel_style" DROP CONSTRAINT "PK_e01e5044f67ff743dc0a547b8e8"`);
        await queryRunner.query(`ALTER TABLE "hotel_hotel_styles_hotel_style" ADD CONSTRAINT "PK_93515c2b2a5f607992c8b2ae000" PRIMARY KEY ("hotelId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c6e80d671f4494cd4c00033f5d"`);
        await queryRunner.query(`ALTER TABLE "hotel_hotel_styles_hotel_style" DROP COLUMN "hotelStyleId"`);
        await queryRunner.query(`ALTER TABLE "hotel_hotel_styles_hotel_style" ADD "hotelStyleId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hotel_hotel_styles_hotel_style" DROP CONSTRAINT "PK_93515c2b2a5f607992c8b2ae000"`);
        await queryRunner.query(`ALTER TABLE "hotel_hotel_styles_hotel_style" ADD CONSTRAINT "PK_e01e5044f67ff743dc0a547b8e8" PRIMARY KEY ("hotelId", "hotelStyleId")`);
        await queryRunner.query(`ALTER TABLE "hotel_languages_language" DROP CONSTRAINT "PK_514ec5d15404c272bb17e01543c"`);
        await queryRunner.query(`ALTER TABLE "hotel_languages_language" ADD CONSTRAINT "PK_5a64c43ef376ca545f95afd9208" PRIMARY KEY ("hotelId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8457bf1103d317e3a87aeefd39"`);
        await queryRunner.query(`ALTER TABLE "hotel_languages_language" DROP COLUMN "languageId"`);
        await queryRunner.query(`ALTER TABLE "hotel_languages_language" ADD "languageId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hotel_languages_language" DROP CONSTRAINT "PK_5a64c43ef376ca545f95afd9208"`);
        await queryRunner.query(`ALTER TABLE "hotel_languages_language" ADD CONSTRAINT "PK_514ec5d15404c272bb17e01543c" PRIMARY KEY ("hotelId", "languageId")`);
        await queryRunner.query(`CREATE INDEX "IDX_c9d7b40237cebf546efb44be33" ON "category_locations_location" ("categoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_144c973be949a5ea0b81fc16d7" ON "room_room_features_room_feature" ("roomFeatureId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ae9dfc32226d4bdd53353f052" ON "room_room_types_room_type" ("roomTypeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4b88b59f78c111f3064df52dc1" ON "hotel_property_amenities_property_amenity" ("propertyAmenityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c6e80d671f4494cd4c00033f5d" ON "hotel_hotel_styles_hotel_style" ("hotelStyleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8457bf1103d317e3a87aeefd39" ON "hotel_languages_language" ("languageId") `);
        await queryRunner.query(`ALTER TABLE "review" ADD CONSTRAINT "FK_b4e9d4998a69f9a84693757eb87" FOREIGN KEY ("tripTypeId") REFERENCES "trip_type"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "room_bed" ADD CONSTRAINT "FK_2f701a2444a9499a40659442b80" FOREIGN KEY ("bedId") REFERENCES "bed"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "category_locations_location" ADD CONSTRAINT "FK_c9d7b40237cebf546efb44be330" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "room_room_features_room_feature" ADD CONSTRAINT "FK_144c973be949a5ea0b81fc16d77" FOREIGN KEY ("roomFeatureId") REFERENCES "room_feature"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_room_types_room_type" ADD CONSTRAINT "FK_6ae9dfc32226d4bdd53353f052a" FOREIGN KEY ("roomTypeId") REFERENCES "room_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hotel_property_amenities_property_amenity" ADD CONSTRAINT "FK_4b88b59f78c111f3064df52dc1f" FOREIGN KEY ("propertyAmenityId") REFERENCES "property_amenity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hotel_hotel_styles_hotel_style" ADD CONSTRAINT "FK_c6e80d671f4494cd4c00033f5d0" FOREIGN KEY ("hotelStyleId") REFERENCES "hotel_style"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hotel_languages_language" ADD CONSTRAINT "FK_8457bf1103d317e3a87aeefd39e" FOREIGN KEY ("languageId") REFERENCES "language"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "hotel_languages_language" DROP CONSTRAINT "FK_8457bf1103d317e3a87aeefd39e"`);
        await queryRunner.query(`ALTER TABLE "hotel_hotel_styles_hotel_style" DROP CONSTRAINT "FK_c6e80d671f4494cd4c00033f5d0"`);
        await queryRunner.query(`ALTER TABLE "hotel_property_amenities_property_amenity" DROP CONSTRAINT "FK_4b88b59f78c111f3064df52dc1f"`);
        await queryRunner.query(`ALTER TABLE "room_room_types_room_type" DROP CONSTRAINT "FK_6ae9dfc32226d4bdd53353f052a"`);
        await queryRunner.query(`ALTER TABLE "room_room_features_room_feature" DROP CONSTRAINT "FK_144c973be949a5ea0b81fc16d77"`);
        await queryRunner.query(`ALTER TABLE "category_locations_location" DROP CONSTRAINT "FK_c9d7b40237cebf546efb44be330"`);
        await queryRunner.query(`ALTER TABLE "room_bed" DROP CONSTRAINT "FK_2f701a2444a9499a40659442b80"`);
        await queryRunner.query(`ALTER TABLE "review" DROP CONSTRAINT "FK_b4e9d4998a69f9a84693757eb87"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8457bf1103d317e3a87aeefd39"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c6e80d671f4494cd4c00033f5d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b88b59f78c111f3064df52dc1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ae9dfc32226d4bdd53353f052"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_144c973be949a5ea0b81fc16d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9d7b40237cebf546efb44be33"`);
        await queryRunner.query(`ALTER TABLE "hotel_languages_language" DROP CONSTRAINT "PK_514ec5d15404c272bb17e01543c"`);
        await queryRunner.query(`ALTER TABLE "hotel_languages_language" ADD CONSTRAINT "PK_5a64c43ef376ca545f95afd9208" PRIMARY KEY ("hotelId")`);
        await queryRunner.query(`ALTER TABLE "hotel_languages_language" DROP COLUMN "languageId"`);
        await queryRunner.query(`ALTER TABLE "hotel_languages_language" ADD "languageId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_8457bf1103d317e3a87aeefd39" ON "hotel_languages_language" ("languageId") `);
        await queryRunner.query(`ALTER TABLE "hotel_languages_language" DROP CONSTRAINT "PK_5a64c43ef376ca545f95afd9208"`);
        await queryRunner.query(`ALTER TABLE "hotel_languages_language" ADD CONSTRAINT "PK_514ec5d15404c272bb17e01543c" PRIMARY KEY ("hotelId", "languageId")`);
        await queryRunner.query(`ALTER TABLE "hotel_hotel_styles_hotel_style" DROP CONSTRAINT "PK_e01e5044f67ff743dc0a547b8e8"`);
        await queryRunner.query(`ALTER TABLE "hotel_hotel_styles_hotel_style" ADD CONSTRAINT "PK_93515c2b2a5f607992c8b2ae000" PRIMARY KEY ("hotelId")`);
        await queryRunner.query(`ALTER TABLE "hotel_hotel_styles_hotel_style" DROP COLUMN "hotelStyleId"`);
        await queryRunner.query(`ALTER TABLE "hotel_hotel_styles_hotel_style" ADD "hotelStyleId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_c6e80d671f4494cd4c00033f5d" ON "hotel_hotel_styles_hotel_style" ("hotelStyleId") `);
        await queryRunner.query(`ALTER TABLE "hotel_hotel_styles_hotel_style" DROP CONSTRAINT "PK_93515c2b2a5f607992c8b2ae000"`);
        await queryRunner.query(`ALTER TABLE "hotel_hotel_styles_hotel_style" ADD CONSTRAINT "PK_e01e5044f67ff743dc0a547b8e8" PRIMARY KEY ("hotelId", "hotelStyleId")`);
        await queryRunner.query(`ALTER TABLE "hotel_property_amenities_property_amenity" DROP CONSTRAINT "PK_f1d5ba5e12b8dfc56db6089307a"`);
        await queryRunner.query(`ALTER TABLE "hotel_property_amenities_property_amenity" ADD CONSTRAINT "PK_a125ce628f13d8dcd15115e4f8e" PRIMARY KEY ("hotelId")`);
        await queryRunner.query(`ALTER TABLE "hotel_property_amenities_property_amenity" DROP COLUMN "propertyAmenityId"`);
        await queryRunner.query(`ALTER TABLE "hotel_property_amenities_property_amenity" ADD "propertyAmenityId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_4b88b59f78c111f3064df52dc1" ON "hotel_property_amenities_property_amenity" ("propertyAmenityId") `);
        await queryRunner.query(`ALTER TABLE "hotel_property_amenities_property_amenity" DROP CONSTRAINT "PK_a125ce628f13d8dcd15115e4f8e"`);
        await queryRunner.query(`ALTER TABLE "hotel_property_amenities_property_amenity" ADD CONSTRAINT "PK_f1d5ba5e12b8dfc56db6089307a" PRIMARY KEY ("propertyAmenityId", "hotelId")`);
        await queryRunner.query(`ALTER TABLE "room_room_types_room_type" DROP CONSTRAINT "PK_090c4a3b7469fb4cd3d9df38475"`);
        await queryRunner.query(`ALTER TABLE "room_room_types_room_type" ADD CONSTRAINT "PK_a7acd938565a8daf63a8f352f41" PRIMARY KEY ("roomId")`);
        await queryRunner.query(`ALTER TABLE "room_room_types_room_type" DROP COLUMN "roomTypeId"`);
        await queryRunner.query(`ALTER TABLE "room_room_types_room_type" ADD "roomTypeId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_6ae9dfc32226d4bdd53353f052" ON "room_room_types_room_type" ("roomTypeId") `);
        await queryRunner.query(`ALTER TABLE "room_room_types_room_type" DROP CONSTRAINT "PK_a7acd938565a8daf63a8f352f41"`);
        await queryRunner.query(`ALTER TABLE "room_room_types_room_type" ADD CONSTRAINT "PK_090c4a3b7469fb4cd3d9df38475" PRIMARY KEY ("roomId", "roomTypeId")`);
        await queryRunner.query(`ALTER TABLE "room_room_features_room_feature" DROP CONSTRAINT "PK_379ccbfb1b706c0014f653870e2"`);
        await queryRunner.query(`ALTER TABLE "room_room_features_room_feature" ADD CONSTRAINT "PK_7f8b1acbd9e3fc084c43734bd9b" PRIMARY KEY ("roomId")`);
        await queryRunner.query(`ALTER TABLE "room_room_features_room_feature" DROP COLUMN "roomFeatureId"`);
        await queryRunner.query(`ALTER TABLE "room_room_features_room_feature" ADD "roomFeatureId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_144c973be949a5ea0b81fc16d7" ON "room_room_features_room_feature" ("roomFeatureId") `);
        await queryRunner.query(`ALTER TABLE "room_room_features_room_feature" DROP CONSTRAINT "PK_7f8b1acbd9e3fc084c43734bd9b"`);
        await queryRunner.query(`ALTER TABLE "room_room_features_room_feature" ADD CONSTRAINT "PK_379ccbfb1b706c0014f653870e2" PRIMARY KEY ("roomId", "roomFeatureId")`);
        await queryRunner.query(`ALTER TABLE "category_locations_location" DROP CONSTRAINT "PK_26b6e9028d7c597535350b05bc4"`);
        await queryRunner.query(`ALTER TABLE "category_locations_location" ADD CONSTRAINT "PK_16c0a15a534e3f86e5dbf1757b9" PRIMARY KEY ("locationId")`);
        await queryRunner.query(`ALTER TABLE "category_locations_location" DROP COLUMN "categoryId"`);
        await queryRunner.query(`ALTER TABLE "category_locations_location" ADD "categoryId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_c9d7b40237cebf546efb44be33" ON "category_locations_location" ("categoryId") `);
        await queryRunner.query(`ALTER TABLE "category_locations_location" DROP CONSTRAINT "PK_16c0a15a534e3f86e5dbf1757b9"`);
        await queryRunner.query(`ALTER TABLE "category_locations_location" ADD CONSTRAINT "PK_26b6e9028d7c597535350b05bc4" PRIMARY KEY ("locationId", "categoryId")`);
        await queryRunner.query(`ALTER TABLE "booking" ALTER COLUMN "createAt" SET DEFAULT '2023-04-19 15:42:49.788'`);
        await queryRunner.query(`ALTER TABLE "receipt" ALTER COLUMN "createAt" SET DEFAULT '2023-04-19 15:42:49.788'`);
        await queryRunner.query(`ALTER TABLE "room_bed" DROP COLUMN "bedId"`);
        await queryRunner.query(`ALTER TABLE "room_bed" ADD "bedId" integer`);
        await queryRunner.query(`ALTER TABLE "bed" DROP CONSTRAINT "PK_828b3f79eab8a8b1de6b6ed6c5a"`);
        await queryRunner.query(`ALTER TABLE "bed" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "bed" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bed" ADD CONSTRAINT "PK_828b3f79eab8a8b1de6b6ed6c5a" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "room_bed" ADD CONSTRAINT "FK_2f701a2444a9499a40659442b80" FOREIGN KEY ("bedId") REFERENCES "bed"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "room_type" DROP CONSTRAINT "PK_abd0f8a4c8a444a84fa2b343353"`);
        await queryRunner.query(`ALTER TABLE "room_type" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "room_type" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "room_type" ADD CONSTRAINT "PK_abd0f8a4c8a444a84fa2b343353" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "room_room_types_room_type" ADD CONSTRAINT "FK_6ae9dfc32226d4bdd53353f052a" FOREIGN KEY ("roomTypeId") REFERENCES "room_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_feature" DROP CONSTRAINT "PK_06829e5737733d39a047f775a66"`);
        await queryRunner.query(`ALTER TABLE "room_feature" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "room_feature" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "room_feature" ADD CONSTRAINT "PK_06829e5737733d39a047f775a66" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "room_room_features_room_feature" ADD CONSTRAINT "FK_144c973be949a5ea0b81fc16d77" FOREIGN KEY ("roomFeatureId") REFERENCES "room_feature"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "language" DROP CONSTRAINT "PK_cc0a99e710eb3733f6fb42b1d4c"`);
        await queryRunner.query(`ALTER TABLE "language" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "language" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "language" ADD CONSTRAINT "PK_cc0a99e710eb3733f6fb42b1d4c" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "hotel_languages_language" ADD CONSTRAINT "FK_8457bf1103d317e3a87aeefd39e" FOREIGN KEY ("languageId") REFERENCES "language"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hotel_style" DROP CONSTRAINT "PK_52239cf25eaead597a583e26766"`);
        await queryRunner.query(`ALTER TABLE "hotel_style" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "hotel_style" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hotel_style" ADD CONSTRAINT "PK_52239cf25eaead597a583e26766" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "hotel_hotel_styles_hotel_style" ADD CONSTRAINT "FK_c6e80d671f4494cd4c00033f5d0" FOREIGN KEY ("hotelStyleId") REFERENCES "hotel_style"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property_amenity" DROP CONSTRAINT "PK_9a5289e5f83bc78d0dbf997a56f"`);
        await queryRunner.query(`ALTER TABLE "property_amenity" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "property_amenity" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "property_amenity" ADD CONSTRAINT "PK_9a5289e5f83bc78d0dbf997a56f" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "hotel_property_amenities_property_amenity" ADD CONSTRAINT "FK_4b88b59f78c111f3064df52dc1f" FOREIGN KEY ("propertyAmenityId") REFERENCES "property_amenity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location_image" DROP CONSTRAINT "PK_dfa981be0cd5c3c2f8c37915564"`);
        await queryRunner.query(`ALTER TABLE "location_image" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "location_image" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "location_image" ADD CONSTRAINT "PK_dfa981be0cd5c3c2f8c37915564" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "review" DROP CONSTRAINT "UQ_b4e9d4998a69f9a84693757eb87"`);
        await queryRunner.query(`ALTER TABLE "review" DROP COLUMN "tripTypeId"`);
        await queryRunner.query(`ALTER TABLE "review" ADD "tripTypeId" integer`);
        await queryRunner.query(`ALTER TABLE "review" ADD CONSTRAINT "UQ_b4e9d4998a69f9a84693757eb87" UNIQUE ("tripTypeId")`);
        await queryRunner.query(`ALTER TABLE "review" ALTER COLUMN "reviewDate" SET DEFAULT '2023-04-19 15:42:49.776'`);
        await queryRunner.query(`ALTER TABLE "trip_type" DROP CONSTRAINT "PK_b80a1e112ae33caa104b8fd0e39"`);
        await queryRunner.query(`ALTER TABLE "trip_type" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "trip_type" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trip_type" ADD CONSTRAINT "PK_b80a1e112ae33caa104b8fd0e39" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "review" ADD CONSTRAINT "FK_b4e9d4998a69f9a84693757eb87" FOREIGN KEY ("tripTypeId") REFERENCES "trip_type"("id") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "category" DROP CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03"`);
        await queryRunner.query(`ALTER TABLE "category" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "category" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "category" ADD CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "category_locations_location" ADD CONSTRAINT "FK_c9d7b40237cebf546efb44be330" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "account" ALTER COLUMN "createAt" SET DEFAULT '2023-04-19 15:42:49.77'`);
        await queryRunner.query(`ALTER TABLE "account" DROP COLUMN "refreshTokenSalt"`);
        await queryRunner.query(`ALTER TABLE "account" DROP COLUMN "iv"`);
        await queryRunner.query(`ALTER TABLE "account" DROP COLUMN "passwordSalt"`);
    }

}
