version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=travel
    ports:
      - 5432:5432
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes: 
      - db:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/travel-care/api/
      - /travel-care/api/node_modules
    depends_on:
      - db
    env_file:
      - docker.env
    environment:
      - NODE_ENV=development  
    links:
      - db
    command: > 
      sh -c "yarn migration:run && yarn start:dev"

volumes:
  db:
    driver: local